BASE <ex:>
CONSTRUCT {
  ?s0 ?p0 _:3 .
  _:3 <ex:a0> _:2 .
  _:2 <ex:b0> <ex:c0> .
  _:5 ?p0 ?o0 .
  _:5 <ex:a0> _:4 .
  _:4 <ex:b0> <ex:c0> .
}
WHERE {
  ?s1 ?p1 _:6 .
  ?s1 ?p1 <ex:a1> .
  ?s1 ?q1 <ex:b1> .
  ?s1 ?q1 <ex:c1> .
  _:7 ?p2 ?o2 .
  ?s3 ?p3 _:8 .
  _:8 <ex:a3> <ex:b3> .
  ?s4 ?p4 _:9 .
  _:9 <ex:a4> <ex:b4> .
  _:9 <ex:c4> <ex:d4> .
  _:9 <ex:c4> <ex:e4> .
  ?s5 ?p5 _:11 .
  _:11 <ex:a5> _:10 .
  _:10 <ex:b5> <ex:c5> .
  _:13 ?p6 ?o6 .
  _:13 <ex:a6> _:12 .
  _:12 <ex:b6> <ex:c6> .
  _:14 <ex:a7> <ex:b7> .
  _:14 <ex:c7> <ex:d7> .
  _:14 <ex:c7> <ex:e7> .
}