SELECT * WHERE {
  _:18 <http://p> ?o .
  _:18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://a> .
  _:18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
}