PREFIX : <https://ex.com/>
SELECT * WHERE {
  <https://ex.com/a> <https://ex.com/a> <https://ex.com/a> .
  <https://ex.com/a> <https://ex.com/a> _:0 .
  _:0 (<https://ex.com/a>/<https://ex.com/a>) <https://ex.com/a> .
}