PREFIX : <https://ex.com/>
SELECT ?a WHERE {
  <https://ex.com/a> ?a <https://ex.com/a> .
  <https://ex.com/a> <https://ex.com/a> _:57 .
  _:57 (<https://ex.com/a>/<https://ex.com/a>) <https://ex.com/a> .
}